### ISSUE TITLE
Received datas are not the same as sent

### ISSUE THREAD

**Issue by jdasilvaav** [huyrua291996/esp32#1]
Hello,

I use two ESP-WROOM32 in order to publish and suscribe to the same topic. 

I publish and I suscribe well but when I show in the terminal the value receive by one of the WROOM32 I got : 
                            I (5815) MQTT_SAMPLE: [APP] Publish data : 3ffc2b60

whereas I sent 0x00 with the other. Do you know how to show the true data?

BR.
Jérémy

**Comment by huyrua291996** [comment]
yeah, I still got this problem. And I am finding the way to solve this

**Comment by jdasilvaav** [comment]
Ok good, I am finding too. Please notify us if you solve this problem.

**Comment by huyrua291996** [comment]
yeah, i just copy cJSON.c and cJSON.h in the folder main. It's work fine. Hope u too

**Comment by jdasilvaav** [comment]
Hi,

The JSON function works well with this line : 

void data_cb(void *self, void *params)
{
    mqtt_client *client = (mqtt_client *)self;
    mqtt_event_data_t *event_data = (mqtt_event_data_t *)params;

    //cJSON *request_json; 
    if(event_data->data_offset == 0) {

      const char *items = "{\"items\": \"huy\"}";

      cJSON *request_json = cJSON_Parse(items);
      char *item=cJSON_GetObjectItem(request_json, "items")->valuestring;

      ESP_LOGI(MQTT_TAG,"[APP TEST] Publish data : %s", item);
      cJSON_Delete(request_json);
      free(topic);
    }
}

but how can I receive the value of the real data?

**Comment by huyrua291996** [comment]
you can use the following code in data_cb 
`
        char *data = malloc(event_data->data_length + 1);
	memcpy(data, event_data->data, event_data->data_length);
	data[event_data->data_length] = 0;
	cJSON *request_json = cJSON_Parse(data);
	char *item = cJSON_GetObjectItem(request_json, "items");
	cJSON_Delete(request_json);
	ESP_LOGI(MQTT_TAG,"[APP] Publish data : %s", item);
	free(data);
`

**Comment by jdasilvaav** [comment]
Hav you tried this function with your received data?

Because it doesn't work for me even if I send data. For example, I send 0x0C01FF and the terminal show : 
I (5295) MQTT_SAMPLE: [APP] Publish data : 3ffc6360
I (5301) MQTT_SAMPLE: [APP] Publish data[3/3 bytes]

**Comment by huyrua291996** [comment]
yeah, i tried it, it work for me. Have you try to publish using MQTTLens with {"items": "abc"} for example ?

**Comment by jdasilvaav** [comment]
I use one ESP32 to publish this values : 0c 01 01. I use MQTTLens to suscribe to the same topic as my second ESP32 Accessory. You can find my MQTTLens result below : 

![image](https://user-images.githubusercontent.com/31218158/30384957-fcfa4e1a-98a5-11e7-87e8-c6e9e32ed3d1.png)

That is give us in hex : 0C 01 01

And below the result by the second ESP32: 

> [MQTT INFO] Data received: 3/3 bytes
> received data is 3ffc32a4

**Comment by jdasilvaav** [comment]
I have tried with `abc` and it works. But it doesn't work with hexadecimal data..

**Comment by huyrua291996** [comment]
Just because the function mqtt_publish use to publish char*
