### ISSUE TITLE
Client destroyed

### ISSUE THREAD

**Issue by gchauvelin** [huyrua291996/esp32#2]
Hello,

I use an ESP WROOM 32 in order to publish to a topic.
The module starts, then it publish to the topic every 10 sec for example. This works only once time, after I have the following message in the terminal :
[MQTT INFO] Read len 0
[MQTT INFO] Read error 128
[MQTT INFO] Closing client socket
[MQTT INFO] Client destroyed

Do you know what is the issue, why my MQTT client is "destroyed"?

Best regards,

Grégory

**Comment by huyrua291996** [comment]
Can u show me your code

**Comment by gchauvelin** [comment]
Hello,

Sorry for the delay. I have solved this issue, the problem was that to modules were publishing to the same topic with the same settings.client_id.

BR,

Grégory
